"use client";

import type React from "react";
import { createContext, useState, useContext, useEffect } from "react";

type Language = "es" | "en";

type LanguageContextType = {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traducciones
const translations = {
  es: {
    // Header
    "header.access": "Acceso",
    "header.search": "Buscar",
    "header.selectBranch": "Seleccionar sucursal",
    "header.loadingBranches": "Cargando sucursales...",
    "header.selectBranchTitle": "Seleccionar sucursal",
    "header.branchesAvailable": "sucursales disponibles",
    "header.noBranches": "No hay sucursales disponibles",
    "header.code": "Código:",
    "header.noResults": "No se encontraron resultados.",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.catalogues": "Catálogos",
    "nav.areas": "Áreas",
    "nav.services": "Servicios",
    "nav.clients": "Clientes",
    "nav.branches": "Sucursales",
    "nav.users": "Usuarios",
    "nav.operations": "Operaciones",
    "nav.appointments": "Citas",
    "nav.reports": "Reportes",
    "nav.shifts": "Turnos",
    "nav.notifications": "Notificaciones",
    "nav.configuration": "Configuración",
    "nav.calendar": "Calendario",
    "nav.forms": "Formularios",
    "nav.tables": "Tablas",
    "nav.uiElements": "Elementos UI",
    "nav.charts": "Gráficos",
    
    // Common
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.create": "Crear",
    "common.view": "Ver",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.export": "Exportar",
    "common.import": "Importar",
    "common.download": "Descargar",
    "common.upload": "Subir",
    "common.close": "Cerrar",
    "common.open": "Abrir",
    "common.yes": "Sí",
    "common.no": "No",
    "common.ok": "Aceptar",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.loading": "Cargando...",
    "common.refresh": "Actualizar",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.warning": "Advertencia",
    "common.info": "Información",
    "common.viewMore": "Ver más",
    "common.clear": "Limpiar",
    
    // Auth
    "auth.signIn": "Iniciar Sesión",
    "auth.signUp": "Registrarse",
    "auth.signOut": "Cerrar Sesión",
    "auth.email": "Correo Electrónico",
    "auth.password": "Contraseña",
    "auth.confirmPassword": "Confirmar Contraseña",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.resetPassword": "Restablecer Contraseña",
    "auth.rememberMe": "Recordarme",
    "auth.back": "Volver",
    "auth.loginDescription": "Ingresa tu usuario/email y contraseña para acceder al sistema de turnos",
    "auth.usernameOrEmail": "Usuario o Email",
    "auth.usernameOrEmailPlaceholder": "usuario o correo@ejemplo.com",
    "auth.passwordPlaceholder": "Ingresa tu contraseña",
    "auth.keepSessionActive": "Mantener sesión iniciada",
    "auth.signingIn": "Iniciando sesión...",
    "auth.fillAllFields": "Por favor completa todos los campos",
    "auth.invalidCredentials": "Credenciales Incorrectas",
    "auth.backToSignIn": "Volver al inicio",
    "auth.recoverPassword": "Recuperar contraseña",
    "auth.recoverPasswordDescription": "Ingresa tu correo para recibir el código de recuperación",
    "auth.emailPlaceholder": "correo@ejemplo.com",
    "auth.sending": "Enviando...",
    "auth.sendCode": "Enviar código",
    "auth.receivedCode": "Código recibido",
    "auth.code": "Código",
    "auth.codePlaceholder": "Código",
    "auth.newPassword": "Nueva contraseña",
    "auth.newPasswordPlaceholder": "Nueva contraseña",
    "auth.verifying": "Verificando...",
    "auth.changePassword": "Cambiar contraseña",
    "auth.passwordChangedSuccess": "¡Contraseña cambiada exitosamente!",
    "auth.passwordChangedMessage": "Ya puedes iniciar sesión con tu nueva contraseña",
    "auth.goToSignIn": "Ir a iniciar sesión",
    "auth.errorSendingCode": "Error al enviar el código",
    "auth.errorChangingPassword": "Error al cambiar la contraseña",
    
    // User types
    "userType.administrator": "Administrador",
    "userType.executive": "Ejecutivo",
    "userType.client": "Cliente",
    "userType.advisor": "Asesor",
    
    // Notifications
    "notifications.title": "Notificaciones",
    "notifications.newShifts": "Nuevos Turnos",
    "notifications.noNewNotifications": "No hay notificaciones nuevas",
    "notifications.viewAll": "Ver todas las notificaciones",
    "notifications.newShift": "Nuevo turno:",
    "notifications.read": "Notificación leída:",
    "notifications.shift": "Turno",
    "notifications.all": "Todas",
    "notifications.unread": "No leídas",
    "notifications.readLabel": "Leídas",
    "notifications.markAsRead": "Marcar como leída",
    "notifications.noNotifications": "No hay notificaciones",
    "notifications.close": "Cerrar",
    
    // Dashboard
    "dashboard.clientsToday": "Clientes del Día",
    "dashboard.shiftsIssuedToday": "Turnos Emitidos Hoy",
    "dashboard.mostRequestedServices": "Servicios más solicitados",
    "dashboard.mostFrequentedAreas": "Áreas Más Frecuentadas",
    "dashboard.basedOnRecentClientVisits": "Basado en visitas recientes de clientes",
    "dashboard.noDataToShow": "No hay datos para mostrar",
    "dashboard.loadingChart": "Cargando gráfico...",
    "dashboard.currentShift": "Turno Actual",
    "dashboard.shiftsToday": "Turnos Hoy",
    "dashboard.averageTime": "Tiempo Promedio",
    "dashboard.attendedClients": "Clientes Atendidos",
    "dashboard.activeBranches": "Sucursales Activas",
    "dashboard.shiftsDistributionByArea": "Distribución de Turnos por Área",
    "dashboard.shifts": "Turnos",
    "dashboard.loading": "Cargando...",
    
    // Service names (for chart labels)
    "services.collection": "Cobranza",
    "services.reports": "Reportes",
    "services.commercial": "Comercial",
    "services.contractService": "Contratar servicio",
    "services.paymentPlans": "Planes de pago",
    "services.serviceContract": "contrato de servicio",
    "services.largeUsers": "Grandes usuarios",
    "services.energyEfficiency": "Eficiencia Energética",
    "services.industrial": "Industrial",
    
    // Months
    "months.january": "Enero",
    "months.february": "Febrero",
    "months.march": "Marzo",
    "months.april": "Abril",
    "months.may": "Mayo",
    "months.june": "Junio",
    "months.july": "Julio",
    "months.august": "Agosto",
    "months.september": "Septiembre",
    "months.october": "Octubre",
    "months.november": "Noviembre",
    "months.december": "Diciembre",
    
    // Areas
    "areas.manageAndConsultAreas": "Gestiona y consulta las áreas del sistema",
    "areas.newArea": "Nueva Área",
    "areas.totalAreas": "Total Áreas",
    "areas.active": "Activas",
    "areas.inactive": "Inactivas",
    "areas.searchArea": "Buscar Área",
    "areas.searchByCodeOrName": "Buscar por código o nombre...",
    "areas.status": "Estado",
    "areas.allStatuses": "Todos los estados",
    "areas.branch": "Sucursal",
    "areas.allBranches": "Todas las sucursales",
    "areas.areaQuery": "Consulta de Áreas",
    "areas.code": "Código",
    "areas.areaName": "Nombre del Área",
    "areas.description": "Descripción",
    "areas.actions": "Acciones",
    "areas.noAreasFound": "No se encontraron áreas",
    "areas.tryAdjustingFilters": "Intente ajustar los filtros de búsqueda",
    "areas.noAreasRegistered": "No hay áreas registradas en el sistema",
    "areas.editArea": "Editar área",
    "areas.deactivateArea": "Inactivar área",
    "areas.activateArea": "Activar área",
    "areas.showing": "Mostrando",
    "areas.of": "de",
    "areas.areas": "áreas",
    "areas.areaList": "Lista de Áreas",
    
    // Services
    "services.manageAndConsultServices": "Gestiona y consulta los servicios del sistema",
    "services.newService": "Nuevo Servicio",
    "services.totalServices": "Total Servicios",
    "services.active": "Activos",
    "services.forClients": "Para Clientes",
    "services.forNonClients": "Para No Clientes",
    "services.searchService": "Buscar Servicio",
    "services.searchByCodeOrName": "Buscar por código o nombre...",
    "services.area": "Área",
    "services.allAreas": "Todas las áreas",
    "services.clientType": "Tipo de Cliente",
    "services.allTypes": "Todos los tipos",
    "services.clients": "Clientes",
    "services.nonClients": "No clientes",
    "services.serviceQuery": "Consulta de Servicios",
    
    // Clients
    "clients.manageAndConsultClients": "Gestiona y consulta los clientes del sistema",
    "clients.newClient": "Nuevo Cliente",
    "clients.clientList": "Lista de Clientes",
    "clients.clientCode": "Código Cliente",
    "clients.name": "Nombre",
    "clients.lastName": "Apellido Paterno",
    "clients.motherLastName": "Apellido Materno",
    "clients.contractType": "Tipo Contrato",
    "clients.address": "Domicilio",
    "clients.premiumClient": "Cliente Premium",
    "clients.status": "Estado",
    "clients.actions": "Acciones",
    "clients.standard": "ESTÁNDAR",
    "clients.allStatuses": "Todos los estados",
    "clients.allTypes": "Todos los tipos",
    "clients.editClient": "Editar cliente",
    "clients.deactivateClient": "Inactivar cliente",
    "clients.activateClient": "Activar cliente",
    "clients.noClientsFound": "No se encontraron clientes",
    "clients.tryAdjustingFilters": "Intente ajustar los filtros de búsqueda",
    "clients.noClientsRegistered": "No hay clientes registrados en el sistema",
    "clients.showing": "Mostrando",
    "clients.of": "de",
    "clients.clients": "clientes",
    "clients.previous": "Anterior",
    "clients.next": "Siguiente",
    "clients.totalClients": "Total Clientes",
    "clients.active": "Activos",
    "clients.inactive": "Inactivos",
    "clients.premium": "PREMIUM",
    "clients.searchClient": "Buscar Cliente",
    "clients.searchByCodeNameSurname": "Buscar por código, nombre, apellido...",
    "clients.clientQuery": "Consulta de Clientes",
    
    // Users
    "users.manageAndConsultUsers": "Gestiona y consulta los usuarios del sistema",
    "users.newUser": "Nuevo Usuario",
    "users.totalUsers": "Total Usuarios",
    "users.active": "Activos",
    "users.inactive": "Inactivos",
    "users.byType": "Por Tipo",
    "users.admin": "Admin",
    "users.executives": "Ejecutivos",
    "users.advisors": "Asesores",
    "users.searchUser": "Buscar Usuario",
    "users.searchByNameSurnameEmail": "Buscar por nombre, apellido o correo...",
    "users.userType": "Tipo de Usuario",
    "users.allTypes": "Todos los tipos",
    "users.administrator": "Administrador",
    "users.executive": "Ejecutivo",
    "users.advisor": "Asesor",
    "users.status": "Estado",
    "users.allStatuses": "Todos los estados",
    "users.userList": "Lista de Usuarios",
    
    // Configuration
    "configuration.title": "Configuración",
    "configuration.successTitle": "¡Operación exitosa!",
    "configuration.active": "ACTIVO",
    "configuration.unsavedChanges": "CAMBIOS SIN GUARDAR",
    "configuration.generalInfo": "Información General",
    "configuration.systemStatus": "Estatus del Sistema",
    "configuration.systemActiveMessage": "El sistema está actualmente activo y funcionando",
    "configuration.companyName": "Nombre de la Empresa *",
    "configuration.systemName": "Nombre del Sistema *",
    "configuration.logoAndAppearance": "Logo y Apariencia",
    "configuration.uploadLightLogo": "Subir Logo Light",
    "configuration.uploadDarkLogo": "Subir Logo Dark",
    "configuration.fileFormats": "Formatos: JPG, PNG, SVG. Máx. 2MB.",
    "configuration.lastUpdate": "Última actualización:",
    "configuration.cancel": "Cancelar",
    "configuration.resetAll": "Restablecer Todo",
    "configuration.saveConfiguration": "Guardar Configuración",
    "configuration.saving": "Guardando...",
    "configuration.resetConfirm": "¿Restablecer toda la configuración a valores por defecto? Los cambios no guardados se perderán.",
    "configuration.cancelConfirm": "Tienes cambios sin guardar. ¿Seguro que quieres cancelar?",
    "configuration.fileTooLarge": "El archivo es demasiado grande. Máximo 2MB.",
    "configuration.invalidFormat": "Formato de archivo no válido. Use JPG, PNG o SVG.",
    "configuration.imageError": "Error al procesar la imagen. Intente con otra.",
    "configuration.fileReadError": "Error al leer el archivo",
    "configuration.saveError": "Error al guardar configuración:",
    "configuration.updateSuccess": "¡Configuración actualizada correctamente!",
    
    // User dropdown translations
    "userDropdown.configuration": "Configuración",
    "userDropdown.myTurns": "Mis Turnos",
    "userDropdown.logout": "Cerrar Sesión",
    "userDropdown.administrator": "Administrador",
    "userDropdown.executive": "Ejecutivo",
    "userDropdown.advisor": "Asesor",
    "userDropdown.user": "Usuario",
    
    // Starter page translations
    "starter.title": "Solicitud de Turnos",
    "starter.welcome": "EL SISTEMA ITZEL LES DA LA BIENVENIDA",
    "starter.subtitle": "Sistema Inteligente de Turnos • CFE",
    "starter.clientType": "TIPO DE CLIENTE",
    "starter.selectProfile": "Seleccione su perfil para acceder a nuestros servicios",
    "starter.notClient": "NO SOY CLIENTE",
    "starter.notClientDesc": "Acceso a servicios públicos y atención general",
    "starter.cfeClient": "SOY CLIENTE CFE",
    "starter.cfeClientDesc": "Atención preferencial y servicios exclusivos",
    "starter.largeUsers": "GRANDES USUARIOS",
    "starter.select": "SELECCIONAR",
    "starter.attention": "¡Atención!",
    "starter.selectBranchFirst": "Por favor seleccione una sucursal en el menú superior antes de continuar.",
    "starter.serviceSelection": "SELECCIÓN DE SERVICIO",
    "starter.client": "Cliente",
    "starter.cfeClientType": "Cliente CFE",
    "starter.notClientType": "No cliente",
    "starter.branch": "Sucursal",
    "starter.timeRemaining": "Tiempo restante:",
    "starter.selectArea": "Seleccione el área:",
    "starter.selectService": "Seleccione el servicio en",
    "starter.noServicesAvailable": "No hay servicios disponibles para esta área",
    "starter.returnToStart": "Regresar al inicio",
    "starter.confirmTurn": "¿Confirmar turno?",
    "starter.confirmTurnDesc": "Está a punto de generar un turno para el servicio seleccionado",
    "starter.area": "Área",
    "starter.cancel": "Cancelar",
    "starter.yesConfirm": "Sí, confirmar turno",
    "starter.generating": "Generando...",
    "starter.warning": "Una vez confirmado, el turno será generado en el sistema y deberá esperar su atención.",
    "starter.serviceAssigned": "¡SERVICIO ASIGNADO!",
    "starter.turnGenerated": "Su turno ha sido generado exitosamente",
    "starter.systemItzel": "SISTEMA ITZEL",
    "starter.cfe": "Comisión Federal de Electricidad",
    "starter.turnNumber": "TURNO No.",
    "starter.service": "Servicio",
    "starter.type": "Tipo",
    "starter.date": "Fecha",
    "starter.time": "Hora",
    "starter.keepTicket": "Por favor conserve este ticket y espere a ser llamado",
    "starter.scanQR": "Escanee el código QR para descargar su ticket",
    "starter.downloadTicket": "📄 Descargar Ticket",
    "starter.cancelTurn": "Cancelar turno",
    "starter.returningIn": "Regresando automáticamente en",
    "starter.seconds": "segundos...",
    "starter.generatingTurn": "Generando su turno...",
    "starter.cancelingTurn": "Cancelando su turno...",
    "starter.confirmCancellation": "Confirmar Cancelación",
    "starter.sureCancel": "¿Estás seguro de que deseas cancelar este turno?",
    "starter.turnToCancel": "Turno a cancelar",
    "starter.noReturn": "No, regresar",
    "starter.yesCancel": "Sí, cancelar turno",
    "starter.turnCanceled": "Turno cancelado exitosamente",
    "starter.privacyNotice": "Aviso de Privacidad",
    
    // Form translations - Areas
    "form.area.title": "Información del Área",
    "form.area.code": "Código del Área",
    "form.area.codePlaceholder": "Ej: CONTA, RECHUM",
    "form.area.codeMax": "Máximo 6 caracteres",
    "form.area.name": "Nombre del Área",
    "form.area.namePlaceholder": "Ej: Contabilidad, Recursos Humanos",
    "form.area.description": "Descripción del Área",
    "form.area.descriptionPlaceholder": "Describe las funciones y responsabilidades del área...",
    "form.area.branch": "Sucursal",
    "form.area.selectBranch": "Selecciona una sucursal",
    "form.area.status": "Estado",
    "form.area.active": "Activo",
    "form.area.inactive": "Inactivo",
    "form.area.additionalConfig": "Configuración Adicional",
    "form.area.create": "Crear Área",
    "form.area.edit": "Editar Área",
    "form.area.createNew": "Crear Nueva Área",
    "form.area.update": "Actualizar Área",
    "form.area.loading": "Cargando formulario...",
    "form.area.created": "Área creada correctamente",
    "form.area.updated": "Área actualizada correctamente",
    "form.area.errorCreate": "Error al crear área",
    "form.area.errorUpdate": "Error al actualizar área",
    "form.area.errorLoad": "Error al cargar los datos del área",
    "form.area.errorInitial": "Error al cargar los datos iniciales",
    "form.area.codeRequired": "El código del área es obligatorio",
    "form.area.codeMaxLength": "El código no puede tener más de 6 caracteres",
    "form.area.nameRequired": "El nombre del área es obligatorio",
    "form.area.descriptionRequired": "La descripción del área es obligatoria",
    "form.area.branchRequired": "Debe seleccionar una sucursal",
    
    // Form translations - Services
    "form.service.title": "Información del Servicio",
    "form.service.name": "Nombre del Servicio",
    "form.service.namePlaceholder": "Ej. Cobro de facturas",
    "form.service.code": "Código del Servicio",
    "form.service.codePlaceholder": "Ej. SVC-001",
    "form.service.codeMax": "Máximo 6 caracteres",
    "form.service.description": "Descripción del Servicio",
    "form.service.descriptionPlaceholder": "Detalles adicionales del servicio...",
    "form.service.area": "Área",
    "form.service.selectArea": "Seleccione un área",
    "form.service.areaBranch": "Sucursal del Área",
    "form.service.areaBranchDesc": "Sucursal a la que pertenece el área seleccionada",
    "form.service.selectAreaFirst": "Seleccione un área",
    "form.service.clientType": "¿Es para clientes o no clientes?",
    "form.service.forClients": "Clientes",
    "form.service.forNonClients": "No clientes",
    "form.service.clientTypeDesc": "Selecciona si este servicio es para clientes o no clientes.",
    "form.service.status": "Estado",
    "form.service.active": "Activo",
    "form.service.inactive": "Inactivo",
    "form.service.create": "Crear Servicio",
    "form.service.edit": "Editar Servicio",
    "form.service.createNew": "Crear Nuevo Servicio",
    "form.service.update": "Actualizar Servicio",
    "form.service.loading": "Cargando datos del servicio...",
    "form.service.loadingAreas": "Cargando áreas...",
    "form.service.created": "Servicio creado correctamente",
    "form.service.updated": "Servicio actualizado correctamente",
    "form.service.errorCreate": "Error al guardar el servicio",
    "form.service.errorLoad": "Error al cargar datos del servicio",
    "form.service.errorLoadAreas": "Error al cargar las áreas",
    "form.service.noAreas": "No hay áreas disponibles. Por favor, cree áreas primero.",
    "form.service.nameRequired": "El nombre del servicio es requerido",
    "form.service.codeRequired": "El código del servicio es requerido",
    "form.service.codeMaxLength": "El código del servicio no puede tener más de 6 caracteres",
    "form.service.areaRequired": "El área es requerida",
    
    // Form translations - Branches
    "form.branch.name": "Nombre de la Sucursal",
    "form.branch.namePlaceholder": "Ej: Sucursal Centro",
    "form.branch.address": "Domicilio",
    "form.branch.addressPlaceholder": "Calle, número, colonia",
    "form.branch.phone": "Teléfono",
    "form.branch.phonePlaceholder": "Ej: 312-123-4567",
    "form.branch.phoneMax": "Máximo 20 caracteres",
    "form.branch.postalCode": "Código Postal",
    "form.branch.postalCodePlaceholder": "Ej: 28000",
    "form.branch.state": "Estado",
    "form.branch.municipality": "Municipio",
    "form.branch.selectState": "Seleccionar Estado",
    "form.branch.selectMunicipality": "Seleccionar Municipio",
    "form.branch.selectStateFirst": "Primero elige un estado",
    "form.branch.branchData": "Datos de la Sucursal",
    "form.branch.assignExecutives": "Asignar Ejecutivos a Sucursal",
    "form.branch.assignAdvisors": "Asignar Asesores a Sucursal",
    "form.branch.editMode": "Modo edición: Puedes agregar más {type} usando el formulario de abajo. Los {type} existentes se muestran en la tabla.",
    "form.branch.executives": "Ejecutivos",
    "form.branch.advisors": "Asesores",
    "form.branch.user": "Usuario",
    "form.branch.selectExecutive": "Seleccionar Ejecutivo",
    "form.branch.selectAdvisor": "Seleccionar Asesor",
    "form.branch.selectUserFirst": "Seleccione primero un Usuario",
    "form.branch.selectService": "Seleccionar Servicio",
    "form.branch.selectAreaFirst": "Primero elija un área",
    "form.branch.selectArea": "Seleccionar Área",
    "form.branch.assignedExecutives": "Ejecutivos Asignados",
    "form.branch.assignedAdvisors": "Asesores Asignados",
    "form.branch.area": "Área",
    "form.branch.service": "Servicio",
    "form.branch.fullName": "Nombre Completo",
    "form.branch.email": "Email",
    "form.branch.action": "Acción",
    "form.branch.removeExecutive": "Eliminar ejecutivo",
    "form.branch.removeAdvisor": "Eliminar asesor",
    "form.branch.create": "Crear Sucursal",
    "form.branch.edit": "Editar Sucursal",
    "form.branch.register": "Registrar Nueva Sucursal",
    "form.branch.update": "Actualizar Sucursal",
    "form.branch.save": "Guardar Sucursal",
    "form.branch.loading": "Cargando datos...",
    "form.branch.errorLoad": "No se pudieron cargar los datos iniciales. Por favor, intente nuevamente.",
    "form.branch.errorSave": "Error al guardar la sucursal:",
    "form.branch.completeFields": "Por favor, complete todos los campos obligatorios.",
    "form.branch.success": "¡Éxito!",
    "form.branch.saved": "Sucursal guardada exitosamente!",
    "form.branch.updated": "Sucursal actualizada exitosamente!",
    "form.branch.error": "Error",
    
    // Form translations - Users
    "form.user.personalInfo": "Información Personal",
    "form.user.contactInfo": "Información de Contacto y Acceso",
    "form.user.officialInfo": "Información Oficial",
    "form.user.profilePhoto": "Foto de Perfil",
    "form.user.systemConfig": "Configuración del Sistema",
    "form.user.name": "Nombre",
    "form.user.namePlaceholder": "Nombre del usuario",
    "form.user.lastName": "Apellido Paterno",
    "form.user.lastNamePlaceholder": "Apellido paterno",
    "form.user.motherLastName": "Apellido Materno",
    "form.user.motherLastNamePlaceholder": "Apellido materno",
    "form.user.birthDate": "Fecha de Nacimiento",
    "form.user.phone": "Teléfono",
    "form.user.phonePlaceholder": "10 dígitos",
    "form.user.email": "Correo Electrónico",
    "form.user.emailPlaceholder": "correo@ejemplo.com",
    "form.user.password": "Contraseña",
    "form.user.newPassword": "Nueva Contraseña (opcional)",
    "form.user.passwordPlaceholder": "Mínimo 6 caracteres",
    "form.user.passwordPlaceholderEdit": "Dejar en blanco para mantener actual",
    "form.user.rfc": "RFC",
    "form.user.rfcPlaceholder": "13 caracteres",
    "form.user.curp": "CURP",
    "form.user.curpPlaceholder": "18 caracteres",
    "form.user.address": "Domicilio",
    "form.user.addressPlaceholder": "Dirección completa del usuario...",
    "form.user.selectImage": "Seleccionar Imagen",
    "form.user.userType": "Tipo de Usuario",
    "form.user.status": "Estado",
    "form.user.active": "Activo",
    "form.user.inactive": "Inactivo",
    "form.user.create": "Crear Usuario",
    "form.user.edit": "Editar Usuario",
    "form.user.createNew": "Crear Nuevo Usuario",
    "form.user.update": "Actualizar Usuario",
    "form.user.loading": "Cargando datos del usuario...",
    "form.user.created": "Usuario creado correctamente. Se ha enviado un correo electrónico de verificación. Por favor, revisa tu bandeja de entrada y haz clic en el enlace de verificación para activar tu cuenta.",
    "form.user.updated": "Usuario actualizado correctamente",
    "form.user.errorCreate": "Error al guardar el usuario",
    "form.user.errorLoad": "Error al cargar datos del usuario",
    "form.user.errorImage": "Por favor seleccione un archivo de imagen válido",
    "form.user.errorImageSize": "La imagen no puede ser mayor a 5MB",
    "form.user.nameRequired": "El nombre es requerido",
    "form.user.emailRequired": "El correo electrónico es requerido",
    "form.user.emailInvalid": "Formato de correo electrónico inválido",
    "form.user.passwordRequired": "La contraseña es requerida para usuarios nuevos",
    "form.user.passwordMin": "La contraseña debe tener al menos 6 caracteres",
    "form.user.rfcRequired": "El RFC es requerido",
    "form.user.rfcLength": "El RFC debe tener exactamente 13 caracteres",
    "form.user.curpRequired": "El CURP es requerido",
    "form.user.curpLength": "El CURP debe tener exactamente 18 caracteres",
    "form.user.addressRequired": "El domicilio es requerido",
    "form.user.phoneInvalid": "El teléfono debe tener 10 dígitos",
    
    // Form translations - Clients
    "form.client.title": "Información del Cliente",
    "form.client.additionalInfo": "Información Adicional",
    "form.client.code": "Código del Cliente",
    "form.client.codePlaceholder": "Ej: CL001",
    "form.client.name": "Nombre",
    "form.client.namePlaceholder": "Nombre",
    "form.client.lastName": "Apellido Paterno",
    "form.client.lastNamePlaceholder": "Apellido paterno",
    "form.client.motherLastName": "Apellido Materno",
    "form.client.motherLastNamePlaceholder": "Apellido materno",
    "form.client.address": "Domicilio",
    "form.client.addressPlaceholder": "Domicilio",
    "form.client.contractType": "Tipo de Contrato",
    "form.client.selectOption": "Selecciona una opción",
    "form.client.monofasica": "Monofásica",
    "form.client.bifasica": "Bifásica",
    "form.client.trifasica": "Trifásica",
    "form.client.premium": "Cliente Premium",
    "form.client.yes": "Sí",
    "form.client.no": "No",
    "form.client.status": "Estado",
    "form.client.active": "Activo",
    "form.client.inactive": "Inactivo",
    "form.client.create": "Crear Cliente",
    "form.client.edit": "Editar Cliente",
    "form.client.createNew": "Crear Nuevo Cliente",
    "form.client.update": "Actualizar Cliente",
    "form.client.loading": "Cargando formulario...",
    "form.client.created": "Cliente creado correctamente",
    "form.client.updated": "Cliente actualizado correctamente",
    "form.client.errorCreate": "Error al guardar cliente",
    "form.client.errorLoad": "Error al cargar los datos del cliente",
    "form.client.notFound": "😅 Eso no existe",
    "form.client.backToList": "Volver al listado",
    "form.client.codeRequired": "El código del cliente es obligatorio",
    "form.client.nameRequired": "El nombre es obligatorio",
    "form.client.lastNameRequired": "El apellido paterno es obligatorio",
    "form.client.addressRequired": "El domicilio es obligatorio",
    "form.client.contractTypeRequired": "El tipo de contrato es obligatorio",
    "form.client.contractCodeRequired": "El código de contrato es obligatorio",
    
    // Common form translations
    "form.cancel": "Cancelar",
    "form.saving": "Guardando...",
    "form.success": "¡Operación exitosa!",
    "form.correctErrors": "Por favor, corrija los errores en el formulario",
    "form.required": "obligatorio",
    
    // Table translations - Common
    "table.loading": "Cargando...",
    "table.error": "Error al cargar",
    "table.retry": "Reintentar",
    "table.noResults": "No se encontraron resultados",
    "table.adjustFilters": "Intente ajustar los filtros de búsqueda",
    "table.noData": "No hay datos registrados en el sistema",
    "table.showing": "Mostrando",
    "table.of": "de",
    "table.previous": "Anterior",
    "table.next": "Siguiente",
    "table.actions": "Acciones",
    "table.edit": "Editar",
    "table.delete": "Eliminar",
    "table.confirmDelete": "¿Está seguro de que desea eliminar",
    "table.deleteSuccess": "eliminado exitosamente",
    "table.deleteError": "Error al eliminar",
    "table.cancel": "Cancelar",
    "table.accept": "Aceptar",
    "table.deleting": "Eliminando...",
    "table.confirmDeletion": "Confirmar Eliminación",
    "table.success": "¡Éxito!",
    "table.errorTitle": "Error",
    "table.thisActionCannotBeUndone": "Esta acción no se puede deshacer.",
    
    // Table translations - Users
    "table.users.photo": "Foto",
    "table.users.fullName": "Nombre Completo",
    "table.users.emailPhone": "Correo / Teléfono",
    "table.users.rfcCurp": "RFC / CURP",
    "table.users.userType": "Tipo de Usuario",
    "table.users.status": "Estado",
    "table.users.loading": "Cargando usuarios...",
    "table.users.error": "⚠️ Error al cargar usuarios",
    "table.users.notFound": "No se encontraron usuarios",
    "table.users.born": "Nacido:",
    "table.users.noPhone": "Sin teléfono",
    "table.users.editUser": "Editar usuario",
    "table.users.deleteUser": "Eliminar usuario",
    "table.users.deleteConfirm": "¿Está seguro de que desea eliminar al usuario",
    "table.users.deleteSuccess": "Usuario eliminado exitosamente",
    "table.users.deleteError": "Error al eliminar usuario:",
    "table.users.showing": "Mostrando {start}-{end} de {total} usuarios",
    "table.users.unknown": "Desconocido",
    "table.users.noDate": "No especificada",
    "table.users.invalidDate": "Fecha inválida",
    
    // Table translations - Services
    "table.services.code": "Código",
    "table.services.name": "Nombre del Servicio",
    "table.services.description": "Descripción",
    "table.services.area": "Área",
    "table.services.clientType": "Tipo de Cliente",
    "table.services.status": "Estado",
    "table.services.loading": "Cargando servicios...",
    "table.services.error": "Error al cargar servicios",
    "table.services.notFound": "No se encontraron servicios",
    "table.services.editService": "Editar servicio",
    "table.services.deleteService": "Eliminar servicio",
    "table.services.deleteConfirm": "¿Seguro que deseas eliminar el servicio",
    "table.services.deleteSuccess": "Servicio eliminado exitosamente",
    "table.services.deleteError": "Error al eliminar el servicio:",
    "table.services.showing": "Mostrando {start}-{end} de {total} servicios",
    "table.services.clients": "Clientes",
    "table.services.nonClients": "No clientes",
    
    // Table translations - Branches
    "table.branches.name": "Nombre",
    "table.branches.address": "Domicilio",
    "table.branches.state": "Estado",
    "table.branches.municipality": "Municipio",
    "table.branches.phone": "Teléfono",
    "table.branches.executives": "Ejecutivos",
    "table.branches.advisors": "Asesores",
    "table.branches.status": "Estado",
    "table.branches.loading": "Cargando sucursales...",
    "table.branches.notFound": "No se encontraron sucursales",
    "table.branches.editBranch": "Editar sucursal",
    "table.branches.deleteBranch": "Eliminar sucursal",
    "table.branches.showing": "Mostrando {start}-{end} de {total} sucursales",
    "table.branches.noData": "No hay sucursales registradas en el sistema",
    
    // Privacy Notice
    "privacy.title": "Aviso de Privacidad y Términos de Uso",
    "privacy.subtitle": "Su información es importante para nosotros. Por favor, lea los siguientes términos.",
    "privacy.dataResponsible": "Responsable de los Datos",
    "privacy.dataResponsibleText": "La Comisión Federal de Electricidad (CFE) es responsable del tratamiento de sus datos personales de acuerdo con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.",
    "privacy.purposeTitle": "Finalidad del Tratamiento de Datos",
    "privacy.purposeText": "Los datos personales que recabamos de usted serán utilizados para las siguientes finalidades necesarias para el servicio:",
    "privacy.purpose1": "Gestión y administración de tu cuenta de usuario",
    "privacy.purpose2": "Comunicación relacionada con los servicios del sistema",
    "privacy.purpose3": "Mejora continua de nuestros servicios",
    "privacy.purpose4": "Cumplimiento de obligaciones legales y regulatorias",
    "privacy.termsTitle": "Términos y Condiciones de Uso",
    "privacy.termsText": "Al utilizar nuestro sistema, aceptas los siguientes términos:",
    "privacy.term1Title": "Responsabilidad:",
    "privacy.term1Text": "Eres responsable de mantener la confidencialidad de tu contraseña y de todas las actividades realizadas desde tu cuenta.",
    "privacy.term2Title": "Uso apropiado:",
    "privacy.term2Text": "Te comprometes a usar el sistema de manera responsable y conforme a las políticas establecidas.",
    "privacy.term3Title": "Datos personales:",
    "privacy.term3Text": "Los datos proporcionados deben ser verídicos y actualizados.",
    "privacy.term4Title": "Seguridad:",
    "privacy.term4Text": "Implementamos medidas de seguridad para proteger tus datos, pero también requieres mantener buenas prácticas de seguridad.",
    "privacy.term5Title": "Modificaciones:",
    "privacy.term5Text": "Nos reservamos el derecho de modificar estos términos, notificándote con anticipación.",
    "privacy.arcoTitle": "Derechos ARCO",
    "privacy.arcoText": "De acuerdo con la Ley Federal de Protección de Datos Personales, puedes ejercer tus derechos ARCO (Acceso, Rectificación, Cancelación y Oposición) sobre tu información personal.",
    "privacy.arcoAccess": "Acceso",
    "privacy.arcoAccessDesc": "Conocer tu información personal en nuestros registros",
    "privacy.arcoRectification": "Rectificación",
    "privacy.arcoRectificationDesc": "Actualizar o corregir datos inexactos",
    "privacy.arcoCancellation": "Cancelación",
    "privacy.arcoCancellationDesc": "Eliminar tu información cuando ya no sea necesaria",
    "privacy.arcoOpposition": "Oposición",
    "privacy.arcoOppositionDesc": "Oponerte a ciertos usos de tus datos",
    "privacy.protectionTitle": "Protección de Datos",
    "privacy.protectionText": "Tus datos están protegidos mediante:",
    "privacy.protection1": "• Cifrado de contraseñas mediante algoritmos seguros",
    "privacy.protection2": "• Protocolos de seguridad en la transmisión de datos",
    "privacy.protection3": "• Acceso restringido a información sensible",
    "privacy.protection4": "• Auditorías periódicas de seguridad",
    "privacy.acceptButton": "He leído y acepto los términos",
    "privacy.acceptFooter": "Al continuar, aceptas el tratamiento de tus datos conforme a este aviso",
    
    // Contract Validation Modal
    "contractValidation.title": "Validación de Cliente",
    "contractValidation.subtitle": "Ingrese su número de contrato",
    "contractValidation.label": "Número de Contrato",
    "contractValidation.placeholder": "Ingrese su número de contrato",
    "contractValidation.required": "Por favor ingrese su número de contrato",
    "contractValidation.notFound": "El número de contrato no se encuentra registrado en el sistema",
    "contractValidation.invalidFormat": "El formato del número de contrato no es válido",
    "contractValidation.networkError": "Error de conexión. Por favor, verifique su conexión a internet.",
    "contractValidation.genericError": "Error al validar el número de contrato. Por favor, intente nuevamente.",
    "contractValidation.cancel": "Cancelar",
    "contractValidation.validate": "Validar",
    "contractValidation.validating": "Validando...",
    
    // Branches
    "branches.branchQuery": "Consulta de Sucursales",
    "branches.branchCatalog": "Catálogo de Sucursales",
    "branches.manageAndConsultBranches": "Gestiona y consulta las sucursales del sistema",
    "branches.newBranch": "Nueva Sucursal",
    "branches.totalBranches": "Total Sucursales",
    "branches.active": "Activas",
    "branches.searchByNameOrAddress": "Buscar por Nombre o Domicilio",
    "branches.searchByNameOrAddressPlaceholder": "Buscar por nombre o domicilio...",
    "branches.state": "Estado",
    "branches.allStates": "Todos los estados",
    "branches.municipality": "Municipio",
    "branches.allMunicipalities": "Todos los municipios",
    "branches.selectState": "Seleccione un estado",
    "branches.branchList": "Lista de Sucursales",
    
    // Shifts
    "shifts.noBranchSelected": "No hay sucursal seleccionada",
    "shifts.selectBranchMessage": "Por favor seleccione una sucursal en el menú superior.",
    "shifts.shiftManagement": "Gestión de Turnos",
    "shifts.branch": "Sucursal",
    "shifts.totalToday": "Total Hoy",
    "shifts.waiting": "En Espera",
    "shifts.inProgress": "En Proceso",
    "shifts.attended": "Atendidos",
    "shifts.canceled": "Cancelados",
    "shifts.attendNextShift": "Atender Próximo Turno",
    "shifts.finishAttention": "Finalizar Atención",
    "shifts.update": "Actualizar",
    "shifts.shiftInAttention": "Turno en Atención",
    "shifts.area": "Área",
    "shifts.service": "Servicio",
    "shifts.client": "Cliente",
    "shifts.attendedBy": "Atendido por",
    "shifts.start": "Inicio",
    "shifts.noShiftInAttention": "No hay turno en atención",
    "shifts.selectNextShiftMessage": "Seleccione \"Atender Próximo Turno\" para comenzar",
    "shifts.nextShifts": "Próximos Turnos",
    "shifts.attendNow": "Atender Ahora",
    "shifts.next": "Siguiente",
    "shifts.noWaitingShifts": "No hay turnos en espera",
    "shifts.newShiftsWillAppear": "Los nuevos turnos aparecerán aquí",
    "shifts.systemInfo": "Información del Sistema",
    "shifts.lastUpdate": "Última actualización:",
    "shifts.allAreas": "Todas las áreas",
    "shifts.viewAllShifts": "Ver todos los turnos",
    "shifts.errorAttendingShift": "Error al atender turno",
    "shifts.errorFinishingShift": "Error al finalizar turno",
    
    // Language
    "language.spanish": "Español",
    "language.english": "English",
    "language.change": "Cambiar idioma",
    
    // Areas translations
    "area.atencionCliente": "Atención al Cliente",
    "area.atencionClienteDesc": "Información, quejas y aclaraciones.",
    "area.cobranza": "Cobranza",
    "area.cobranzaDesc": "Convenios, adeudos y reconexiones",
    "area.facturacion": "Facturación",
    "area.facturacionDesc": "Servicios de facturación y pagos",
    "area.conexiones": "Conexiones",
    "area.conexionesDesc": "Nuevas conexiones y reinstalaciones",
    "area.serviciosTecnicos": "Servicios Técnicos",
    "area.serviciosTecnicosDesc1": "Revisión, cambio y calibración de medidores",
    "area.serviciosTecnicosDesc2": "Inspecciones, dictámenes y asesoría",
    "area.contratacion": "Contratación",
    "area.contratacionDesc": "Contratar servicio",
    "area.informacionConsultas": "Información y Consultas",
    "area.informacionConsultasDesc": "Asesorías e información de requisitos",
    "area.recursosHumanos": "Recursos Humanos",
    "area.recursosHumanosDesc": "Gestión de personal y recursos humanos",
    "area.reportes": "Reportes",
    "area.reportesDesc": "Área para reportar incidentes",
    "shifts.pending": "pendientes",
    "shifts.pendingCount": "({count} pendientes)",
    
    // Services translations
    "service.dictamenTecnico": "Dictamen Técnico",
    "service.dictamenTecnicoDesc": "Evaluación y certificación de instalaciones",
    "service.inspeccionInstalacion": "Inspección de Instalación",
    "service.inspeccionInstalacionDesc": "Inspección de Instalación",
    "service.consultaRecibo": "Consulta de Recibo",
    "service.consultaReciboDesc": "Consultar estado de cuenta y pagos",
    "service.reporteFallas": "Reporte de Fallas",
    "service.reporteFallasDesc": "Reportar interrupciones del servicio",
    "service.cambioTitularidad": "Cambio de Titularidad",
    "service.cambioTitularidadDesc": "Cambio de propietario del servicio",
    "service.postesPeligrosos": "Postes Peligrosos",
    "service.postesPeligrososDesc": "Postes inclinados, cables sueltos, accidentes.",
    "service.transformadoresDanados": "Transformadores Dañados",
    "service.transformadoresDanadosDesc": "Fallas en equipos de distribución",
  },
  en: {
    // Header
    "header.access": "Access",
    "header.search": "Search",
    "header.selectBranch": "Select branch",
    "header.loadingBranches": "Loading branches...",
    "header.selectBranchTitle": "Select branch",
    "header.branchesAvailable": "branches available",
    "header.noBranches": "No branches available",
    "header.code": "Code:",
    "header.noResults": "No results found.",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.catalogues": "Catalogues",
    "nav.areas": "Areas",
    "nav.services": "Services",
    "nav.clients": "Clients",
    
    // Configuration page translations
    "configuration.title": "Configuration",
    "configuration.successTitle": "Success",
    "configuration.active": "Active",
    "configuration.unsavedChanges": "Unsaved Changes",
    "configuration.generalInfo": "General Information",
    "configuration.systemStatus": "System Status",
    "configuration.systemActiveMessage": "System is running normally",
    "configuration.companyName": "Company Name",
    "configuration.systemName": "System Name",
    "configuration.logoAndAppearance": "Logo and Appearance",
    "configuration.uploadLightLogo": "Upload Light Logo",
    "configuration.uploadDarkLogo": "Upload Dark Logo",
    "configuration.fileFormats": "Formats: JPG, PNG, SVG. Max. 2MB.",
    "configuration.lastUpdate": "Last update:",
    "configuration.cancel": "Cancel",
    "configuration.resetAll": "Reset All",
    "configuration.saveConfiguration": "Save Configuration",
    "configuration.saving": "Saving...",
    "configuration.resetConfirm": "Reset all configuration to default values? Unsaved changes will be lost.",
    "configuration.cancelConfirm": "You have unsaved changes. Are you sure you want to cancel?",
    "configuration.fileTooLarge": "File is too large. Maximum 2MB.",
    "configuration.invalidFormat": "Invalid file format. Use JPG, PNG or SVG.",
    "configuration.imageError": "Error processing image. Try with another one.",
    "configuration.fileReadError": "Error reading file",
    "configuration.saveError": "Error saving configuration:",
    "configuration.updateSuccess": "Configuration updated successfully!",
    
    // User dropdown translations
    "userDropdown.configuration": "Configuration",
    "userDropdown.myTurns": "My Turns",
    "userDropdown.logout": "Log Out",
    "userDropdown.administrator": "Administrator",
    "userDropdown.executive": "Executive",
    "userDropdown.advisor": "Advisor",
    "userDropdown.user": "User",
    
    // Starter page translations
    "starter.title": "Turn Request",
    "starter.welcome": "WELCOME TO ITZEL",
    "starter.subtitle": "Intelligent Turn System • CFE",
    "starter.clientType": "CLIENT TYPE",
    "starter.selectProfile": "Select your profile to access our services",
    "starter.notClient": "I AM NOT A CLIENT",
    "starter.notClientDesc": "Access to public services and general attention",
    "starter.cfeClient": "I AM A CFE CLIENT",
    "starter.cfeClientDesc": "Preferential attention and exclusive services",
    "starter.largeUsers": "LARGE USERS",
    "starter.select": "SELECT",
    "starter.attention": "Attention!",
    "starter.selectBranchFirst": "Please select a branch in the top menu before continuing.",
    "starter.serviceSelection": "SERVICE SELECTION",
    "starter.client": "Client",
    "starter.cfeClientType": "CFE Client",
    "starter.notClientType": "Not a client",
    "starter.branch": "Branch",
    "starter.timeRemaining": "Time remaining:",
    "starter.selectArea": "Select the area:",
    "starter.selectService": "Select the service in",
    "starter.noServicesAvailable": "No services available for this area",
    "starter.returnToStart": "Return to start",
    "starter.confirmTurn": "Confirm turn?",
    "starter.confirmTurnDesc": "You are about to generate a turn for the selected service",
    "starter.area": "Area",
    "starter.cancel": "Cancel",
    "starter.yesConfirm": "Yes, confirm turn",
    "starter.generating": "Generating...",
    "starter.warning": "Once confirmed, the turn will be generated in the system and you will need to wait for your attention.",
    "starter.serviceAssigned": "SERVICE ASSIGNED!",
    "starter.turnGenerated": "Your turn has been generated successfully",
    "starter.systemItzel": "ITZEL SYSTEM",
    "starter.cfe": "Federal Electricity Commission",
    "starter.turnNumber": "TURN No.",
    "starter.service": "Service",
    "starter.type": "Type",
    "starter.date": "Date",
    "starter.time": "Time",
    "starter.keepTicket": "Please keep this ticket and wait to be called",
    "starter.scanQR": "Scan the QR code to download your ticket",
    "starter.downloadTicket": "📄 Download Ticket",
    "starter.cancelTurn": "Cancel turn",
    "starter.returningIn": "Automatically returning in",
    "starter.seconds": "seconds...",
    "starter.generatingTurn": "Generating your turn...",
    "starter.cancelingTurn": "Canceling your turn...",
    "starter.confirmCancellation": "Confirm Cancellation",
    "starter.sureCancel": "Are you sure you want to cancel this turn?",
    "starter.turnToCancel": "Turn to cancel",
    "starter.noReturn": "No, return",
    "starter.yesCancel": "Yes, cancel turn",
    "starter.turnCanceled": "Turn canceled successfully",
    "starter.privacyNotice": "Privacy Notice",
    
    // Form translations - Areas
    "form.area.title": "Area Information",
    "form.area.code": "Area Code",
    "form.area.codePlaceholder": "Ex: CONTA, RECHUM",
    "form.area.codeMax": "Maximum 6 characters",
    "form.area.name": "Area Name",
    "form.area.namePlaceholder": "Ex: Accounting, Human Resources",
    "form.area.description": "Area Description",
    "form.area.descriptionPlaceholder": "Describe the functions and responsibilities of the area...",
    "form.area.branch": "Branch",
    "form.area.selectBranch": "Select a branch",
    "form.area.status": "Status",
    "form.area.active": "Active",
    "form.area.inactive": "Inactive",
    "form.area.additionalConfig": "Additional Configuration",
    "form.area.create": "Create Area",
    "form.area.edit": "Edit Area",
    "form.area.createNew": "Create New Area",
    "form.area.update": "Update Area",
    "form.area.loading": "Loading form...",
    "form.area.created": "Area created successfully",
    "form.area.updated": "Area updated successfully",
    "form.area.errorCreate": "Error creating area",
    "form.area.errorUpdate": "Error updating area",
    "form.area.errorLoad": "Error loading area data",
    "form.area.errorInitial": "Error loading initial data",
    "form.area.codeRequired": "Area code is required",
    "form.area.codeMaxLength": "Code cannot exceed 6 characters",
    "form.area.nameRequired": "Area name is required",
    "form.area.descriptionRequired": "Area description is required",
    "form.area.branchRequired": "You must select a branch",
    
    // Form translations - Services
    "form.service.title": "Service Information",
    "form.service.name": "Service Name",
    "form.service.namePlaceholder": "Ex. Bill collection",
    "form.service.code": "Service Code",
    "form.service.codePlaceholder": "Ex. SVC-001",
    "form.service.codeMax": "Maximum 6 characters",
    "form.service.description": "Service Description",
    "form.service.descriptionPlaceholder": "Additional service details...",
    "form.service.area": "Area",
    "form.service.selectArea": "Select an area",
    "form.service.areaBranch": "Area Branch",
    "form.service.areaBranchDesc": "Branch to which the selected area belongs",
    "form.service.selectAreaFirst": "Select an area",
    "form.service.clientType": "Is it for clients or non-clients?",
    "form.service.forClients": "Clients",
    "form.service.forNonClients": "Non-clients",
    "form.service.clientTypeDesc": "Select whether this service is for clients or non-clients.",
    "form.service.status": "Status",
    "form.service.active": "Active",
    "form.service.inactive": "Inactive",
    "form.service.create": "Create Service",
    "form.service.edit": "Edit Service",
    "form.service.createNew": "Create New Service",
    "form.service.update": "Update Service",
    "form.service.loading": "Loading service data...",
    "form.service.loadingAreas": "Loading areas...",
    "form.service.created": "Service created successfully",
    "form.service.updated": "Service updated successfully",
    "form.service.errorCreate": "Error saving service",
    "form.service.errorLoad": "Error loading service data",
    "form.service.errorLoadAreas": "Error loading areas",
    "form.service.noAreas": "No areas available. Please create areas first.",
    "form.service.nameRequired": "Service name is required",
    "form.service.codeRequired": "Service code is required",
    "form.service.codeMaxLength": "Service code cannot exceed 6 characters",
    "form.service.areaRequired": "Area is required",
    
    // Form translations - Branches
    "form.branch.name": "Branch Name",
    "form.branch.namePlaceholder": "Ex: Downtown Branch",
    "form.branch.address": "Address",
    "form.branch.addressPlaceholder": "Street, number, neighborhood",
    "form.branch.phone": "Phone",
    "form.branch.phonePlaceholder": "Ex: 312-123-4567",
    "form.branch.phoneMax": "Maximum 20 characters",
    "form.branch.postalCode": "Postal Code",
    "form.branch.postalCodePlaceholder": "Ex: 28000",
    "form.branch.state": "State",
    "form.branch.municipality": "Municipality",
    "form.branch.selectState": "Select State",
    "form.branch.selectMunicipality": "Select Municipality",
    "form.branch.selectStateFirst": "First choose a state",
    "form.branch.branchData": "Branch Data",
    "form.branch.assignExecutives": "Assign Executives to Branch",
    "form.branch.assignAdvisors": "Assign Advisors to Branch",
    "form.branch.editMode": "Edit mode: You can add more {type} using the form below. Existing {type} are shown in the table.",
    "form.branch.executives": "Executives",
    "form.branch.advisors": "Advisors",
    "form.branch.user": "User",
    "form.branch.selectExecutive": "Select Executive",
    "form.branch.selectAdvisor": "Select Advisor",
    "form.branch.selectUserFirst": "First select a User",
    "form.branch.selectService": "Select Service",
    "form.branch.selectAreaFirst": "First choose an area",
    "form.branch.selectArea": "Select Area",
    "form.branch.assignedExecutives": "Assigned Executives",
    "form.branch.assignedAdvisors": "Assigned Advisors",
    "form.branch.area": "Area",
    "form.branch.service": "Service",
    "form.branch.fullName": "Full Name",
    "form.branch.email": "Email",
    "form.branch.action": "Action",
    "form.branch.removeExecutive": "Remove executive",
    "form.branch.removeAdvisor": "Remove advisor",
    "form.branch.create": "Create Branch",
    "form.branch.edit": "Edit Branch",
    "form.branch.register": "Register New Branch",
    "form.branch.update": "Update Branch",
    "form.branch.save": "Save Branch",
    "form.branch.loading": "Loading data...",
    "form.branch.errorLoad": "Could not load initial data. Please try again.",
    "form.branch.errorSave": "Error saving branch:",
    "form.branch.completeFields": "Please complete all required fields.",
    "form.branch.success": "Success!",
    "form.branch.saved": "Branch saved successfully!",
    "form.branch.updated": "Branch updated successfully!",
    "form.branch.error": "Error",
    
    // Form translations - Users
    "form.user.personalInfo": "Personal Information",
    "form.user.contactInfo": "Contact and Access Information",
    "form.user.officialInfo": "Official Information",
    "form.user.profilePhoto": "Profile Photo",
    "form.user.systemConfig": "System Configuration",
    "form.user.name": "Name",
    "form.user.namePlaceholder": "User name",
    "form.user.lastName": "Last Name",
    "form.user.lastNamePlaceholder": "Last name",
    "form.user.motherLastName": "Mother's Last Name",
    "form.user.motherLastNamePlaceholder": "Mother's last name",
    "form.user.birthDate": "Date of Birth",
    "form.user.phone": "Phone",
    "form.user.phonePlaceholder": "10 digits",
    "form.user.email": "Email",
    "form.user.emailPlaceholder": "email@example.com",
    "form.user.password": "Password",
    "form.user.newPassword": "New Password (optional)",
    "form.user.passwordPlaceholder": "Minimum 6 characters",
    "form.user.passwordPlaceholderEdit": "Leave blank to keep current",
    "form.user.rfc": "RFC",
    "form.user.rfcPlaceholder": "13 characters",
    "form.user.curp": "CURP",
    "form.user.curpPlaceholder": "18 characters",
    "form.user.address": "Address",
    "form.user.addressPlaceholder": "Complete user address...",
    "form.user.selectImage": "Select Image",
    "form.user.userType": "User Type",
    "form.user.status": "Status",
    "form.user.active": "Active",
    "form.user.inactive": "Inactive",
    "form.user.create": "Create User",
    "form.user.edit": "Edit User",
    "form.user.createNew": "Create New User",
    "form.user.update": "Update User",
    "form.user.loading": "Loading user data...",
    "form.user.created": "User created successfully. A verification email has been sent. Please check your inbox and click the verification link to activate your account.",
    "form.user.updated": "User updated successfully",
    "form.user.errorCreate": "Error saving user",
    "form.user.errorLoad": "Error loading user data",
    "form.user.errorImage": "Please select a valid image file",
    "form.user.errorImageSize": "Image cannot be larger than 5MB",
    "form.user.nameRequired": "Name is required",
    "form.user.emailRequired": "Email is required",
    "form.user.emailInvalid": "Invalid email format",
    "form.user.passwordRequired": "Password is required for new users",
    "form.user.passwordMin": "Password must be at least 6 characters",
    "form.user.rfcRequired": "RFC is required",
    "form.user.rfcLength": "RFC must be exactly 13 characters",
    "form.user.curpRequired": "CURP is required",
    "form.user.curpLength": "CURP must be exactly 18 characters",
    "form.user.addressRequired": "Address is required",
    "form.user.phoneInvalid": "Phone must have 10 digits",
    
    // Form translations - Clients
    "form.client.title": "Client Information",
    "form.client.additionalInfo": "Additional Information",
    "form.client.code": "Client Code",
    "form.client.codePlaceholder": "Ex: CL001",
    "form.client.name": "Name",
    "form.client.namePlaceholder": "Name",
    "form.client.lastName": "Last Name",
    "form.client.lastNamePlaceholder": "Last name",
    "form.client.motherLastName": "Mother's Last Name",
    "form.client.motherLastNamePlaceholder": "Mother's last name",
    "form.client.address": "Address",
    "form.client.addressPlaceholder": "Address",
    "form.client.contractType": "Contract Type",
    "form.client.selectOption": "Select an option",
    "form.client.monofasica": "Single-phase",
    "form.client.bifasica": "Two-phase",
    "form.client.trifasica": "Three-phase",
    "form.client.premium": "Premium Client",
    "form.client.yes": "Yes",
    "form.client.no": "No",
    "form.client.status": "Status",
    "form.client.active": "Active",
    "form.client.inactive": "Inactive",
    "form.client.create": "Create Client",
    "form.client.edit": "Edit Client",
    "form.client.createNew": "Create New Client",
    "form.client.update": "Update Client",
    "form.client.loading": "Loading form...",
    "form.client.created": "Client created successfully",
    "form.client.updated": "Client updated successfully",
    "form.client.errorCreate": "Error saving client",
    "form.client.errorLoad": "Error loading client data",
    "form.client.notFound": "😅 That doesn't exist",
    "form.client.backToList": "Back to list",
    "form.client.codeRequired": "Client code is required",
    "form.client.nameRequired": "Name is required",
    "form.client.lastNameRequired": "Last name is required",
    "form.client.addressRequired": "Address is required",
    "form.client.contractTypeRequired": "Contract type is required",
    "form.client.contractCodeRequired": "Contract code is required",
    
    // Common form translations
    "form.cancel": "Cancel",
    "form.saving": "Saving...",
    "form.success": "Success!",
    "form.correctErrors": "Please correct the errors in the form",
    "form.required": "required",
    
    // Table translations - Common
    "table.loading": "Loading...",
    "table.error": "Error loading",
    "table.retry": "Retry",
    "table.noResults": "No results found",
    "table.adjustFilters": "Try adjusting the search filters",
    "table.noData": "No data registered in the system",
    "table.showing": "Showing",
    "table.of": "of",
    "table.previous": "Previous",
    "table.next": "Next",
    "table.actions": "Actions",
    "table.edit": "Edit",
    "table.delete": "Delete",
    "table.confirmDelete": "Are you sure you want to delete",
    "table.deleteSuccess": "deleted successfully",
    "table.deleteError": "Error deleting",
    "table.cancel": "Cancel",
    "table.accept": "Accept",
    "table.deleting": "Deleting...",
    "table.confirmDeletion": "Confirm Deletion",
    "table.success": "Success!",
    "table.errorTitle": "Error",
    "table.thisActionCannotBeUndone": "This action cannot be undone.",
    
    // Table translations - Users
    "table.users.photo": "Photo",
    "table.users.fullName": "Full Name",
    "table.users.emailPhone": "Email / Phone",
    "table.users.rfcCurp": "RFC / CURP",
    "table.users.userType": "User Type",
    "table.users.status": "Status",
    "table.users.loading": "Loading users...",
    "table.users.error": "⚠️ Error loading users",
    "table.users.notFound": "No users found",
    "table.users.born": "Born:",
    "table.users.noPhone": "No phone",
    "table.users.editUser": "Edit user",
    "table.users.deleteUser": "Delete user",
    "table.users.deleteConfirm": "Are you sure you want to delete user",
    "table.users.deleteSuccess": "User deleted successfully",
    "table.users.deleteError": "Error deleting user:",
    "table.users.showing": "Showing {start}-{end} of {total} users",
    "table.users.unknown": "Unknown",
    "table.users.noDate": "Not specified",
    "table.users.invalidDate": "Invalid date",
    
    // Table translations - Services
    "table.services.code": "Code",
    "table.services.name": "Service Name",
    "table.services.description": "Description",
    "table.services.area": "Area",
    "table.services.clientType": "Client Type",
    "table.services.status": "Status",
    "table.services.loading": "Loading services...",
    "table.services.error": "Error loading services",
    "table.services.notFound": "No services found",
    "table.services.editService": "Edit service",
    "table.services.deleteService": "Delete service",
    "table.services.deleteConfirm": "Are you sure you want to delete service",
    "table.services.deleteSuccess": "Service deleted successfully",
    "table.services.deleteError": "Error deleting service:",
    "table.services.showing": "Showing {start}-{end} of {total} services",
    "table.services.clients": "Clients",
    "table.services.nonClients": "Non-clients",
    
    // Table translations - Branches
    "table.branches.name": "Name",
    "table.branches.address": "Address",
    "table.branches.state": "State",
    "table.branches.municipality": "Municipality",
    "table.branches.phone": "Phone",
    "table.branches.executives": "Executives",
    "table.branches.advisors": "Advisors",
    "table.branches.status": "Status",
    "table.branches.loading": "Loading branches...",
    "table.branches.notFound": "No branches found",
    "table.branches.editBranch": "Edit branch",
    "table.branches.deleteBranch": "Delete branch",
    "table.branches.showing": "Showing {start}-{end} of {total} branches",
    "table.branches.noData": "No branches registered in the system",
    
    // Privacy Notice
    "privacy.title": "Privacy Notice and Terms of Use",
    "privacy.subtitle": "Your information is important to us. Please read the following terms.",
    "privacy.dataResponsible": "Data Controller",
    "privacy.dataResponsibleText": "The Federal Electricity Commission (CFE) is responsible for the processing of your personal data in accordance with the Federal Law on Protection of Personal Data Held by Private Parties.",
    "privacy.purposeTitle": "Purpose of Data Processing",
    "privacy.purposeText": "The personal data we collect from you will be used for the following purposes necessary for the service:",
    "privacy.purpose1": "Management and administration of your user account",
    "privacy.purpose2": "Communication related to system services",
    "privacy.purpose3": "Continuous improvement of our services",
    "privacy.purpose4": "Compliance with legal and regulatory obligations",
    "privacy.termsTitle": "Terms and Conditions of Use",
    "privacy.termsText": "By using our system, you accept the following terms:",
    "privacy.term1Title": "Responsibility:",
    "privacy.term1Text": "You are responsible for maintaining the confidentiality of your password and all activities performed from your account.",
    "privacy.term2Title": "Appropriate use:",
    "privacy.term2Text": "You agree to use the system responsibly and in accordance with established policies.",
    "privacy.term3Title": "Personal data:",
    "privacy.term3Text": "The data provided must be truthful and up-to-date.",
    "privacy.term4Title": "Security:",
    "privacy.term4Text": "We implement security measures to protect your data, but you also need to maintain good security practices.",
    "privacy.term5Title": "Modifications:",
    "privacy.term5Text": "We reserve the right to modify these terms, notifying you in advance.",
    "privacy.arcoTitle": "ARCO Rights",
    "privacy.arcoText": "In accordance with the Federal Law on Protection of Personal Data, you can exercise your ARCO rights (Access, Rectification, Cancellation and Opposition) over your personal information.",
    "privacy.arcoAccess": "Access",
    "privacy.arcoAccessDesc": "Know your personal information in our records",
    "privacy.arcoRectification": "Rectification",
    "privacy.arcoRectificationDesc": "Update or correct inaccurate data",
    "privacy.arcoCancellation": "Cancellation",
    "privacy.arcoCancellationDesc": "Delete your information when it is no longer necessary",
    "privacy.arcoOpposition": "Opposition",
    "privacy.arcoOppositionDesc": "Object to certain uses of your data",
    "privacy.protectionTitle": "Data Protection",
    "privacy.protectionText": "Your data is protected through:",
    "privacy.protection1": "• Password encryption using secure algorithms",
    "privacy.protection2": "• Security protocols in data transmission",
    "privacy.protection3": "• Restricted access to sensitive information",
    "privacy.protection4": "• Periodic security audits",
    "privacy.acceptButton": "I have read and accept the terms",
    "privacy.acceptFooter": "By continuing, you accept the processing of your data in accordance with this notice",
    
    // Contract Validation Modal
    "contractValidation.title": "Client Validation",
    "contractValidation.subtitle": "Enter your contract number",
    "contractValidation.label": "Contract Number",
    "contractValidation.placeholder": "Enter your contract number",
    "contractValidation.required": "Please enter your contract number",
    "contractValidation.notFound": "The contract number is not registered in the system",
    "contractValidation.invalidFormat": "The contract number format is invalid",
    "contractValidation.networkError": "Connection error. Please check your internet connection.",
    "contractValidation.genericError": "Error validating contract number. Please try again.",
    "contractValidation.cancel": "Cancel",
    "contractValidation.validate": "Validate",
    "contractValidation.validating": "Validating...",
    
    "nav.branches": "Branches",
    "nav.users": "Users",
    "nav.operations": "Operations",
    "nav.appointments": "Appointments",
    "nav.reports": "Reports",
    "nav.shifts": "Shifts",
    "nav.notifications": "Notifications",
    "nav.configuration": "Configuration",
    "nav.calendar": "Calendar",
    "nav.forms": "Forms",
    "nav.tables": "Tables",
    "nav.uiElements": "UI Elements",
    "nav.charts": "Charts",
    
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.create": "Create",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.import": "Import",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.close": "Close",
    "common.open": "Open",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.loading": "Loading...",
    "common.refresh": "Refresh",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Information",
    "common.viewMore": "View more",
    "common.clear": "Clean",
    
    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.signOut": "Sign Out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.forgotPassword": "Forgot your password?",
    "auth.resetPassword": "Reset Password",
    "auth.rememberMe": "Remember me",
    "auth.back": "Back",
    "auth.loginDescription": "Enter your username/email and password to access the shift system",
    "auth.usernameOrEmail": "Username or Email",
    "auth.usernameOrEmailPlaceholder": "username or email@example.com",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.keepSessionActive": "Keep session active",
    "auth.signingIn": "Signing in...",
    "auth.fillAllFields": "Please fill in all fields",
    "auth.invalidCredentials": "Invalid Credentials",
    "auth.backToSignIn": "Back to sign in",
    "auth.recoverPassword": "Recover Password",
    "auth.recoverPasswordDescription": "Enter your email to receive the recovery code",
    "auth.emailPlaceholder": "email@example.com",
    "auth.sending": "Sending...",
    "auth.sendCode": "Send code",
    "auth.receivedCode": "Received code",
    "auth.code": "Code",
    "auth.codePlaceholder": "Code",
    "auth.newPassword": "New Password",
    "auth.newPasswordPlaceholder": "New password",
    "auth.verifying": "Verifying...",
    "auth.changePassword": "Change Password",
    "auth.passwordChangedSuccess": "Password changed successfully!",
    "auth.passwordChangedMessage": "You can now sign in with your new password",
    "auth.goToSignIn": "Go to sign in",
    "auth.errorSendingCode": "Error sending code",
    "auth.errorChangingPassword": "Error changing password",
    
    // User types
    "userType.administrator": "Administrator",
    "userType.executive": "Executive",
    "userType.client": "Client",
    "userType.advisor": "Advisor",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.newShifts": "New Shifts",
    "notifications.noNewNotifications": "No new notifications",
    "notifications.viewAll": "View all notifications",
    "notifications.newShift": "New shift:",
    "notifications.read": "Notification read:",
    "notifications.shift": "Shift",
    "notifications.all": "All",
    "notifications.unread": "Unread",
    "notifications.readLabel": "Read",
    "notifications.markAsRead": "Mark as read",
    "notifications.noNotifications": "No notifications",
    "notifications.close": "Close",
    
    // Dashboard
    "dashboard.clientsToday": "Today's Clients",
    "dashboard.shiftsIssuedToday": "Shifts Issued Today",
    "dashboard.mostRequestedServices": "Most Requested Services",
    "dashboard.mostFrequentedAreas": "Most Frequented Areas",
    "dashboard.basedOnRecentClientVisits": "Based on recent client visits",
    "dashboard.noDataToShow": "No data to show",
    "dashboard.loadingChart": "Loading chart...",
    "dashboard.currentShift": "Current Shift",
    "dashboard.shiftsToday": "Shifts Today",
    "dashboard.averageTime": "Average Time",
    "dashboard.attendedClients": "Attended Clients",
    "dashboard.activeBranches": "Active Branches",
    "dashboard.shiftsDistributionByArea": "Shifts Distribution by Area",
    "dashboard.shifts": "Shifts",
    "dashboard.loading": "Loading...",
    
    // Service names (for chart labels)
    "services.collection": "Collection",
    "services.reports": "Reports",
    "services.commercial": "Commercial",
    "services.contractService": "Contract service",
    "services.paymentPlans": "Payment plans",
    "services.serviceContract": "service contract",
    "services.largeUsers": "Large users",
    "services.energyEfficiency": "Energy Efficiency",
    "services.industrial": "Industrial",
    
    // Months
    "months.january": "January",
    "months.february": "February",
    "months.march": "March",
    "months.april": "April",
    "months.may": "May",
    "months.june": "June",
    "months.july": "July",
    "months.august": "August",
    "months.september": "September",
    "months.october": "October",
    "months.november": "November",
    "months.december": "December",
    
    // Areas
    "areas.manageAndConsultAreas": "Manage and consult system areas",
    "areas.newArea": "New Area",
    "areas.totalAreas": "Total Areas",
    "areas.active": "Active",
    "areas.inactive": "Inactive",
    "areas.searchArea": "Search Area",
    "areas.searchByCodeOrName": "Search by code or name...",
    "areas.status": "Status",
    "areas.allStatuses": "All statuses",
    "areas.branch": "Branch",
    "areas.allBranches": "All branches",
    "areas.areaQuery": "Area Query",
    "areas.code": "Code",
    "areas.areaName": "Area Name",
    "areas.description": "Description",
    "areas.actions": "Actions",
    "areas.noAreasFound": "No areas found",
    "areas.tryAdjustingFilters": "Try adjusting search filters",
    "areas.noAreasRegistered": "No areas registered in the system",
    "areas.editArea": "Edit area",
    "areas.deactivateArea": "Deactivate area",
    "areas.activateArea": "Activate area",
    "areas.showing": "Showing",
    "areas.of": "of",
    "areas.areas": "areas",
    "areas.areaList": "Area List",
    
    // Services
    "services.manageAndConsultServices": "Manage and consult system services",
    "services.newService": "New Service",
    "services.totalServices": "Total Services",
    "services.active": "Active",
    "services.forClients": "For Clients",
    "services.forNonClients": "For Non-Clients",
    "services.searchService": "Search Service",
    "services.searchByCodeOrName": "Search by code or name...",
    "services.area": "Area",
    "services.allAreas": "All areas",
    "services.clientType": "Client Type",
    "services.allTypes": "All types",
    "services.clients": "Clients",
    "services.nonClients": "Non-clients",
    "services.serviceQuery": "Service Query",
    
    // Clients
    "clients.manageAndConsultClients": "Manage and consult system clients",
    "clients.newClient": "New Client",
    "clients.clientList": "Client List",
    "clients.clientCode": "Client Code",
    "clients.name": "Name",
    "clients.lastName": "Last Name",
    "clients.motherLastName": "Mother's Last Name",
    "clients.contractType": "Contract Type",
    "clients.address": "Address",
    "clients.premiumClient": "Premium Client",
    "clients.status": "Status",
    "clients.actions": "Actions",
    "clients.standard": "STANDARD",
    "clients.allStatuses": "All statuses",
    "clients.allTypes": "All types",
    "clients.editClient": "Edit client",
    "clients.deactivateClient": "Deactivate client",
    "clients.activateClient": "Activate client",
    "clients.noClientsFound": "No clients found",
    "clients.tryAdjustingFilters": "Try adjusting search filters",
    "clients.noClientsRegistered": "No clients registered in the system",
    "clients.showing": "Showing",
    "clients.of": "of",
    "clients.clients": "clients",
    "clients.previous": "Previous",
    "clients.next": "Next",
    "clients.totalClients": "Total Clients",
    "clients.active": "Active",
    "clients.inactive": "Inactive",
    "clients.premium": "PREMIUM",
    "clients.searchClient": "Search Client",
    "clients.searchByCodeNameSurname": "Search by code, name, surname...",
    "clients.clientQuery": "Client Query",
    
    // Users
    "users.manageAndConsultUsers": "Manage and consult system users",
    "users.newUser": "New User",
    "users.totalUsers": "Total Users",
    "users.active": "Active",
    "users.inactive": "Inactive",
    "users.byType": "By Type",
    "users.admin": "Admin",
    "users.executives": "Executives",
    "users.advisors": "Advisors",
    "users.searchUser": "Search User",
    "users.searchByNameSurnameEmail": "Search by name, surname or email...",
    "users.userType": "User Type",
    "users.allTypes": "All types",
    "users.administrator": "Administrator",
    "users.executive": "Executive",
    "users.advisor": "Advisor",
    "users.status": "Status",
    "users.allStatuses": "All statuses",
    "users.userList": "User List",
    
    
    // Branches
    "branches.branchQuery": "Branch Query",
    "branches.branchCatalog": "Branch Catalog",
    "branches.manageAndConsultBranches": "Manage and consult system branches",
    "branches.newBranch": "New Branch",
    "branches.totalBranches": "Total Branches",
    "branches.active": "Active",
    "branches.searchByNameOrAddress": "Search by Name or Address",
    "branches.searchByNameOrAddressPlaceholder": "Search by name or address...",
    "branches.state": "State",
    "branches.allStates": "All states",
    "branches.municipality": "Municipality",
    "branches.allMunicipalities": "All municipalities",
    "branches.selectState": "Select a state",
    "branches.branchList": "Branch List",
    
    // Shifts
    "shifts.noBranchSelected": "No branch selected",
    "shifts.selectBranchMessage": "Please select a branch from the top menu.",
    "shifts.shiftManagement": "Shift Management",
    "shifts.branch": "Branch",
    "shifts.totalToday": "Total Today",
    "shifts.waiting": "Waiting",
    "shifts.inProgress": "In Progress",
    "shifts.attended": "Attended",
    "shifts.canceled": "Canceled",
    "shifts.attendNextShift": "Attend Next Shift",
    "shifts.finishAttention": "Finish Attention",
    "shifts.update": "Update",
    "shifts.shiftInAttention": "Shift in Attention",
    "shifts.area": "Area",
    "shifts.service": "Service",
    "shifts.client": "Client",
    "shifts.attendedBy": "Attended by",
    "shifts.start": "Start",
    "shifts.noShiftInAttention": "No shift in attention",
    "shifts.selectNextShiftMessage": "Select \"Attend Next Shift\" to begin",
    "shifts.nextShifts": "Next Shifts",
    "shifts.attendNow": "Attend Now",
    "shifts.next": "Next",
    "shifts.noWaitingShifts": "No waiting shifts",
    "shifts.newShiftsWillAppear": "New shifts will appear here",
    "shifts.systemInfo": "System Information",
    "shifts.lastUpdate": "Last update:",
    "shifts.allAreas": "All areas",
    "shifts.viewAllShifts": "View all shifts",
    "shifts.errorAttendingShift": "Error attending shift",
    "shifts.errorFinishingShift": "Error finishing shift",
    
    // Language
    "language.spanish": "Español",
    "language.english": "English",
    "language.change": "Change language",
    
    // Areas translations
    "area.atencionCliente": "Customer Service",
    "area.atencionClienteDesc": "Information, complaints, and clarifications.",
    "area.cobranza": "Collections",
    "area.cobranzaDesc": "Agreements, debts, and reconnections",
    "area.facturacion": "Billing",
    "area.facturacionDesc": "Billing and payment services",
    "area.conexiones": "Connections",
    "area.conexionesDesc": "New connections and reinstallations",
    "area.serviciosTecnicos": "Technical Services",
    "area.serviciosTecnicosDesc1": "Review, change, and calibration of meters",
    "area.serviciosTecnicosDesc2": "Inspections, opinions, and advice",
    "area.contratacion": "Contracting",
    "area.contratacionDesc": "Contract service",
    "area.informacionConsultas": "Information and Consultations",
    "area.informacionConsultasDesc": "Advice and information on requirements",
    "area.recursosHumanos": "Human Resources",
    "area.recursosHumanosDesc": "Personnel and human resources management",
    "area.reportes": "Reports",
    "area.reportesDesc": "Area to report incidents",
    "shifts.pending": "pending",
    "shifts.pendingCount": "({count} pending)",
    
    // Services translations
    "service.dictamenTecnico": "Technical Opinion",
    "service.dictamenTecnicoDesc": "Evaluation and certification of installations",
    "service.inspeccionInstalacion": "Installation Inspection",
    "service.inspeccionInstalacionDesc": "Installation Inspection",
    "service.consultaRecibo": "Receipt Inquiry",
    "service.consultaReciboDesc": "Check account status and payments",
    "service.reporteFallas": "Failure Report",
    "service.reporteFallasDesc": "Report service interruptions",
    "service.cambioTitularidad": "Change of Ownership",
    "service.cambioTitularidadDesc": "Change of service owner",
    "service.postesPeligrosos": "Dangerous Poles",
    "service.postesPeligrososDesc": "Inclined poles, loose cables, accidents.",
    "service.transformadoresDanados": "Damaged Transformers",
    "service.transformadoresDanadosDesc": "Failures in distribution equipment",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>("es");
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    // This code will only run on the client side
    const savedLanguage = localStorage.getItem("language") as Language | null;
    const initialLanguage = savedLanguage || "es"; // Default to Spanish

    setLanguageState(initialLanguage);
    setIsInitialized(true);
  }, []);

  useEffect(() => {
    if (isInitialized) {
      localStorage.setItem("language", language);
    }
  }, [language, isInitialized]);

  const toggleLanguage = () => {
    setLanguageState((prevLanguage) => (prevLanguage === "es" ? "en" : "es"));
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
